#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/','f','a',
        'n','n','i','n','g','/','w','o','r','k','s','p','a','c','e','/','t','o',
        'o','l','s','/','g','c','c','-','l','i','n','a','r','o','-','7','.','5',
        '.','0','-','2','0','1','9','.','1','2','-','x','8','6','_','6','4','_',
        'a','r','m','-','l','i','n','u','x','-','g','n','u','e','a','b','i','h',
        'f','/','b','i','n','/','a','r','m','-','l','i','n','u','x','-','g','n',
        'u','e','a','b','i','h','f','-','g','c','c',' ','-','I','.',' ','-','I',
        '.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ','-',
        'f','P','I','C',' ','-','D','O','P','E','N','S','S','L','_','P','I','C',
        ' ','-','D','O','P','E','N','S','S','L','_','T','H','R','E','A','D','S',
        ' ','-','D','_','R','E','E','N','T','R','A','N','T',' ','-','D','D','S',
        'O','_','D','L','F','C','N',' ','-','D','H','A','V','E','_','D','L','F',
        'C','N','_','H',' ','-','f','P','I','C',' ','-','O','3',' ','-','W','a',
        'l','l','\0'
    };
    #define PLATFORM "platform: linux-armv4"
    #define DATE "built on: Sun Apr 21 00:26:31 2024"
#endif
